# Generated by Django 2.0.7 on 2018-07-08 19:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('was_completed_at', models.DateField(null=True)),
                ('to_be_completed_by', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('comment', models.TextField(null=True)),
                ('link', models.URLField(null=True)),
                ('was_completed_at', models.DateField(null=True)),
                ('to_be_completed_by', models.DateField(null=True)),
                ('recurring', models.BooleanField()),
                ('repeat_at', models.DateTimeField(null=True)),
                ('priority', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('project', models.ForeignKey(default='Inbox', on_delete=django.db.models.deletion.PROTECT, to='tasks.Project')),
            ],
        ),
    ]
